version: 2
project_name: s5

builds:
  -
    id: "s5"
    binary: s5
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    main: .
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-checksum"
  split: true

changelog:
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'
